#!/bin/sh

# Upload Code Coverage
#
# Uploads code coverage report to Code Climate

echo "Upload Code Coverage"

# Make sure cc-test-reporter is installed
command -v cc-test-reporter >/dev/null 2>&1 || {
	read -e -p "cc-test-reporter not installed. Would you like to install it? [y/N]: " CONTINUE
	if [ "${CONTINUE}" == "y" ]; then
        # Download cc-test-reporter
        curl -L -o cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 --progress-bar
        chmod 755 cc-test-reporter

        # Move cc-test-reporter to /usr/local/bin so we dont have to download it again
        read -e -p "cc-test-reporter installed. Would you like it moved to /usr/local/bin for permanent keeping? [y/N]: " CONTINUE
        if [ "${CONTINUE}" == "y" ]; then
            mv cc-test-reporter /usr/local/bin
            echo "Done."
        fi

	else
		echo "aborting...";
        exit 1;
	fi
}

# Make sure slather is installed
command -v slather >/dev/null 2>&1 || {
    read -e -p "slather not installed. Would you like to install it? [y/N]: " CONTINUE
    if [ "${CONTINUE}" == "y" ]; then
        sudo gem install slather
    else
        echo "aborting...";
        exit 1;
    fi
}


# Run before-build. this sets up the test reporter
cc-test-reporter before-build -d
slather
cc-test-reporter after-build -d

# Cleanup
rm cc-test-reporter > /dev/null 2>&1
